#!/usr/bin/env ruby

require_relative "./lib/find_key_by_value"

translation_key = FindKeyByValue.run(ARGV[0])

if translation_key
  system("ack", translation_key)
else
  puts "No key found for value: #{ARGV[0]}"
end
