#!/usr/bin/env ruby

require_relative "./lib/find_key_by_value"

translation_key = FindKeyByValue.run(ARGV[0])

puts "Translation key: #{translation_key}"

if translation_key
  system("grep -rn \"#{translation_key}\" --include=\*.{rb,slim,js,ts,vue} ./app ./lib ./spec")
else
  puts "No key found"
end
